"""Rendered-output storage backends.

The job database stores status/timestamps only. Rendered document bytes go
through this small backend interface so hosted deployments can move them out
of process memory without changing the upload/status/download API.
"""

from __future__ import annotations

import json
import os
import shutil
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Protocol


class OutputStore(Protocol):
    def put_many(self, job_id: str, data: dict[str, bytes], expires_at: float) -> None:
        ...

    def get(self, job_id: str, fmt: str) -> bytes | None:
        ...

    def delete_job(self, job_id: str, formats: list[str]) -> None:
        ...


class MemoryOutputStore:
    """Process-local output cache. Default for local/dev compatibility."""

    def __init__(self) -> None:
        self._outputs: dict[str, dict] = {}

    def put_many(self, job_id: str, data: dict[str, bytes], expires_at: float) -> None:
        self._outputs[job_id] = {"expires": expires_at, "blobs": dict(data)}

    def get(self, job_id: str, fmt: str) -> bytes | None:
        entry = self._outputs.get(job_id)
        if not entry:
            return None
        if entry["expires"] < time.time():
            self._outputs.pop(job_id, None)
            return None
        return entry["blobs"].get(fmt)

    def delete_job(self, job_id: str, formats: list[str]) -> None:
        self._outputs.pop(job_id, None)


class FilesystemOutputStore:
    """Simple durable backend useful for tests and single-host deployments."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, job_id: str, fmt: str) -> Path:
        # Formats are generated by the app, but keep path handling literal so
        # a future odd format key cannot escape the job directory.
        return self.root / job_id / urllib.parse.quote(fmt, safe="")

    def put_many(self, job_id: str, data: dict[str, bytes], expires_at: float) -> None:
        job_dir = self.root / job_id
        job_dir.mkdir(parents=True, exist_ok=True)
        for fmt, blob in data.items():
            self._path(job_id, fmt).write_bytes(blob)

    def get(self, job_id: str, fmt: str) -> bytes | None:
        path = self._path(job_id, fmt)
        return path.read_bytes() if path.exists() else None

    def delete_job(self, job_id: str, formats: list[str]) -> None:
        shutil.rmtree(self.root / job_id, ignore_errors=True)


class SupabaseStorageOutputStore:
    """Private Supabase Storage bucket backend using the REST API.

    The bucket should be private. This server uploads/downloads with the
    service-role key; users still download through PBICompass's authenticated
    ``/jobs/{id}/download`` endpoint, preserving tenant checks.
    """

    def __init__(self, url: str, service_role_key: str, bucket: str,
                 prefix: str = "outputs", timeout: float = 30.0) -> None:
        self.url = url.rstrip("/")
        self.key = service_role_key
        self.bucket = bucket.strip("/")
        self.prefix = prefix.strip("/")
        self.timeout = timeout
        if not self.url or not self.key or not self.bucket:
            raise RuntimeError(
                "Supabase output storage needs SUPABASE_URL, "
                "SUPABASE_SERVICE_ROLE_KEY, and PBICOMPASS_OUTPUT_BUCKET."
            )

    def _object_name(self, job_id: str, fmt: str) -> str:
        safe_fmt = urllib.parse.quote(fmt, safe="")
        return f"{self.prefix}/{job_id}/{safe_fmt}" if self.prefix else f"{job_id}/{safe_fmt}"

    def _object_url(self, object_name: str) -> str:
        encoded = urllib.parse.quote(object_name, safe="/._-")
        return f"{self.url}/storage/v1/object/{self.bucket}/{encoded}"

    def _bucket_object_url(self) -> str:
        return f"{self.url}/storage/v1/object/{self.bucket}"

    def _headers(self, extra: dict[str, str] | None = None) -> dict[str, str]:
        headers = {
            "apikey": self.key,
            "authorization": f"Bearer {self.key}",
        }
        if extra:
            headers.update(extra)
        return headers

    def _request(self, method: str, object_name: str, body: bytes | None = None,
                 headers: dict[str, str] | None = None) -> bytes:
        req = urllib.request.Request(
            self._object_url(object_name),
            data=body,
            headers=self._headers(headers),
            method=method,
        )
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            return resp.read()

    def _bucket_request(self, method: str, body: bytes,
                        headers: dict[str, str] | None = None) -> bytes:
        req = urllib.request.Request(
            self._bucket_object_url(),
            data=body,
            headers=self._headers(headers),
            method=method,
        )
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            return resp.read()

    def put_many(self, job_id: str, data: dict[str, bytes], expires_at: float) -> None:
        written: list[str] = []
        try:
            for fmt, blob in data.items():
                name = self._object_name(job_id, fmt)
                try:
                    self._request(
                        "POST", name, blob,
                        {"content-type": "application/octet-stream", "x-upsert": "true"},
                    )
                except urllib.error.HTTPError as exc:
                    if exc.code not in (400, 409):
                        raise
                    # Some Storage API versions prefer PUT for overwrites.
                    self._request(
                        "PUT", name, blob,
                        {"content-type": "application/octet-stream", "x-upsert": "true"},
                    )
                written.append(fmt)
        except Exception:
            self.delete_job(job_id, written)
            raise

    def get(self, job_id: str, fmt: str) -> bytes | None:
        try:
            return self._request("GET", self._object_name(job_id, fmt))
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                return None
            raise

    def delete_job(self, job_id: str, formats: list[str]) -> None:
        paths = [self._object_name(job_id, fmt) for fmt in formats]
        if not paths:
            return
        try:
            self._bucket_request(
                "DELETE",
                json.dumps({"prefixes": paths}).encode("utf-8"),
                {"content-type": "application/json"},
            )
        except urllib.error.HTTPError as exc:
            if exc.code != 404:
                raise


def output_store_from_env() -> OutputStore:
    backend = (os.environ.get("PBICOMPASS_OUTPUT_STORE") or "memory").strip().lower()
    if backend in ("", "memory", "in-memory"):
        return MemoryOutputStore()
    if backend in ("filesystem", "file", "local"):
        root = os.environ.get("PBICOMPASS_OUTPUT_DIR") or "/data/pbicompass-outputs"
        return FilesystemOutputStore(root)
    if backend in ("supabase", "supabase-storage"):
        return SupabaseStorageOutputStore(
            os.environ.get("SUPABASE_URL") or "",
            os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or "",
            os.environ.get("PBICOMPASS_OUTPUT_BUCKET") or "pbicompass-outputs",
            prefix=os.environ.get("PBICOMPASS_OUTPUT_PREFIX") or "outputs",
        )
    raise RuntimeError(f"Unknown PBICOMPASS_OUTPUT_STORE backend: {backend}")
